services:
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=omar
      - MONGO_INITDB_ROOT_PASSWORD=omar
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=omar
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=omar
      - ME_CONFIG_MONGODB_ADMINPASSWORD=omar
      - ME_CONFIG_MONGODB_SERVER=mongodb
    links:
      - mongodb
    networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge

volumes:
  mongo: