server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service
          uri: lb:http://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service
          uri: lb:http://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/user/**
        - id: hotel-service
          uri: lb:http://HOTEL-SERVICE
          predicates:
            - Path=/api/v1/hotel/**
        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
        - id: reservation-service
          uri: lb:http://RESERVATION-SERVICE
          predicates:
            - Path=/api/v1/reservation/**
        - id: room-service
          uri: lb:http://ROOM-SERVICE
          predicates:
            - Path=/api/v1/room/**
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    urls:
      - url: http://localhost:8000/v3/api-docs
        name: authentication-service
      - url: http://localhost:8010/v3/api-docs
        name: hotel-service
      - url: http://localhost:8040/v3/api-docs
        name: payment-service
      - url: http://localhost:8030/v3/api-docs
        name: reservation-service
      - url: http://localhost:8020/v3/api-docs
        name: room-service


