version: '3.8'
services:
  postgres:
    container_name: room
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: room-db
    ports:
      - "5434:5432"
    volumes:
      - postgres-data-room:/var/lib/postgresql/data

volumes:
  postgres-data-room: