version: '3.8'
services:
  postgres:
    container_name: hotel
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel-db
    expose:
      - "5433"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-hotel:/var/lib/postgresql/data

volumes:
  postgres-data-hotel: