version: '3.8'
services:
  postgres:
    container_name: payment
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment-db
    ports:
      - "5436:5432"
    volumes:
      - postgres-data-payment:/var/lib/postgresql/data

volumes:
  postgres-data-payment: