version: '3.8'
services:
  postgres:
    container_name: authentication
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-auth:/var/lib/postgresql/data

volumes:
  postgres-data-auth: